### ISSUE TITLE
Background removal

### ISSUE THREAD

**Issue by smallfly** [gaomingqi/Track-Anything#19]
Hello,

Your segmentation and tracking are impressive! I was wondering if there is a way to remove the background once a 'subject' is being tracked?

Thank you.

**Comment by gaomingqi** [comment]
Hello, thanks for your interest! Sure, we will make background removal available soon! Actually, we have implemented background removal in tools/painter.py but have not yet connected it with tracking results. 

https://github.com/gaomingqi/Track-Anything/blob/6d3925046a26cbb2219645ed6ecc1bae487da5f7/tools/painter.py#L159

It takes one video frame (np.array, HxWx3) and the corresponding mask (np.array, HxW) as inputs and outputs a PIL.Image with the segmented objects and transparent background.

:strawberry: If you have cloned or forked our code, you can have a try by importing background_remover in tracker/base_tracker.py: 

```from tools.painter import background_remover```

Then, replace the lines in tracker/base_tracker.py: 

https://github.com/gaomingqi/Track-Anything/blob/6d3925046a26cbb2219645ed6ecc1bae487da5f7/tracker/base_tracker.py#L99-L102

with

`painted_image = np.array(background_remover(painted_image, (final_mask>0).astype('uint8')))`

Finally, run Track-Anything as normal, you will have the frames without background :champagne:. Thanks.

**Comment by smallfly** [comment]
Hello,

Thanks for the quick and detailed reply.

I had seen the 'brackground_remover()' method but was not sure of its main purpose.

I just tried to apply the changes to 'base_tracker.py' but I get the following error once the tracking is complete. My video is 1920x1080 with  a duration of 11sec, at 30fps.

Thank you!

Tracking image: 100%
Traceback (most recent call last):
 File "C:\Users\...\anaconda3\envs\track-anything\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\...\anaconda3\envs\track-anything\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\Users\...\anaconda3\envs\track-anything\lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\...\anaconda3\envs\track-anything\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\...\anaconda3\envs\track-anything\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\...\anaconda3\envs\track-anything\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\...\Tracking_and_Segmentation\Track-Anything\app.py", line 258, in vos_tracking_video
    video_output = generate_video_from_frames(video_state["painted_images"], output_path="./result/track/{}".format(video_state["video_name"]), fps=fps) # import video_input to name the output video
  File "D:\...\Tracking_and_Segmentation\Track-Anything\app.py", line 337, in generate_video_from_frames
    torchvision.io.write_video(output_path, frames, fps=fps, video_codec="libx264")
  File "C:\Users\...\anaconda3\envs\track-anything\lib\site-packages\torchvision\io\video.py", line 131, in write_video
    frame = av.VideoFrame.from_ndarray(img, format="rgb24")
  File "av\video\frame.pyx", line 409, in av.video.frame.VideoFrame.from_ndarray
  File "av\utils.pyx", line 80, in av.utils.check_ndarray_shape
ValueError: Unexpected numpy array shape (1080, 1920, 4)

**Comment by gaomingqi** [comment]
Yes, the error appears since torchvision.io.write_video only considers 3-channel frames, but we feed it with 4-channel frames (RGB + Alpha, corresponding to the transparency). In my previous response, I tried generating videos with transparent backgrounds. 

Instead of making backgrounds transparent, is masking backgrounds with a single colour an acceptable alternative? To do so, you can just replace the code (in my previous response):

```
painted_image = np.array(background_remover(painted_image, (final_mask>0).astype('uint8')))
```

with:

```
painted_image = mask_painter(painted_image, (final_mask==0).astype('uint8'), mask_color=0, mask_alpha=1, contour_width=0)
```

where mask_color is the colour index, and 0 indicates black. More colour maps are available at:

https://github.com/gaomingqi/Track-Anything/blob/482cc0db8118bb0e3506e2c2e88959af8187398c/assets/color_map_with_id.png 

mask_alpha is the transparency of the painted mask. Thanks.

**Comment by smallfly** [comment]
Hello, Thanks again. This works great.

Masking backgrounds with a single color is perfect to run our tests, but for sure the end goal would be to generate videos with a transparent background.

**Comment by chris-hndz** [comment]
Hello @gaomingqi !
Thanks for your amazing work!
I have made the replacements that you indicate in the previous messages, and the background remover works very well!
How can we change the color of the removed background, so that instead of white it is chroma color (68 in your color map)?

Thank you very much!
